options:
  zabbix-server-ip-address:
    type: string
    default: "x.x.x.x"
    description: "IP address for zabbix server."
  zabbix-templates:
    type: string
    default: "template1,template2"
    description: "comma separated template names of registering to zabbix server."

