#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

juju-log 'run config-changed hook.'

server=`config-get zabbix-server-ip-address`
hostname=`hostname`

#sudo usermod -a -G adm zabbix
sudo gpasswd -a zabbix adm

sed -i -e "s/^Server=.*/Server=$server/g" /etc/zabbix/zabbix_agentd.conf
sed -i -e "s/^ServerActive=.*/ServerActive=$server/g" /etc/zabbix/zabbix_agentd.conf
sed -i -e "s/^Hostname=.*/Hostname=$hostname/g" /etc/zabbix/zabbix_agentd.conf
sed -i -e "s/^# EnableRemoteCommands=0/EnableRemoteCommands=1/g" /etc/zabbix/zabbix_agentd.conf

install -g root -o root -m 644 files/userparameter_general.conf /etc/zabbix/zabbix_agentd.d/userparameter_general.conf

#hooks/start
