#!/bin/bash
# This will be run when the service is being torn down, allowing you to disable
# it in various ways..
# For example, if your web app uses a text file to signal to the load balancer
# that it is live... you could remove it and sleep for a bit to allow the load
# balancer to stop sending traffic.
# rm /srv/webroot/server-live.txt && sleep 30
 
dpkg -l zabbix-agent | grep -Eq "^ii"
if [ $? -eq 0 ]
then
  sudo dpkg -r zabbix-agent
  #sudo dpkg -P zabbix-agent
fi
 
sudo gpasswd -d zabbix adm
